rep

diff --git a/https_ssl/0-world_wide_web b/https_ssl/0-world_wide_web
--- a/https_ssl/0-world_wide_web
+++ b/https_ssl/0-world_wide_web
@@ -1,23 +1,33 @@
 #!/usr/bin/env bash
-# Displaying info about information about subdomains.
-# Script: 0-world_wide_web
+#Displaying info about information about subdomains.
 
-domain_information() {
-    line=$(dig "$2"."$1" +short)
-    if [ -n "$line" ]; then
-        record_type=$(dig "$2"."$1" | awk 'NR==1 {print $4}')
-        echo "The subdomain $2 is a $record_type record and points to $line"
-    else
-        echo "Error: Unable to retrieve information for $2.$1."
+domaindis_info() {
+    local subdomain="$1"
+    local domain="$2"
+    local record_type
+    record_type=$(dig +short -t ANY "$subdomain.$domain" | awk 'NR==1 {print $4}')
+#if dig fails exit
+    if [ -z "$record_type" ]; then
+        echo "Error: Unable to retrieve information for $subdomain.$domain."
+        exit 1
     fi
+    
+    local destination
+    destination=$(dig +short "$subdomain.$domain" | head -n 1)
+    echo "The subdomain $subdomain is a $record_type record and points to $destination"
 }
+#mainscript
 
-if [ "$#" == 1 ]; then
-    domain_information "$1" "www"
-    domain_information "$1" "lb-01"
-    domain_information "$1" "web-01"
-    domain_information "$1" "web-02"
-elif [ "$#" == 2 ]; then
-    domain_information "$1" "$2"
+#confirms doain provision
+if [ -z "$1" ]; then
+    echo "Usage: $0 <domain>"
+    exit 1
 fi
 
+domain="HByjdlql.tech"
+subdomains=("www" "lb-01" "web-01" "web-02")
+
+# Loop through subdomains and display information
+for sub in "${subdomains[@]}"; do
+    domaindis_info "$sub" "$domain"
+done
